# Generated by Django 2.0.4 on 2018-04-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_description', models.CharField(blank=True, max_length=200, null=True)),
                ('title_btn', models.CharField(blank=True, default='Join', max_length=50, null=True)),
                ('title_btn_url', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
