# Generated by Django 2.0.4 on 2018-04-14 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180414_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video_embed',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
