# Generated by Django 2.0.4 on 2018-04-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180414_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
