# Generated by Django 2.0.4 on 2018-04-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180415_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='leave_capture',
            field=models.BooleanField(default=True),
        ),
    ]
