# Generated by Django 2.0.4 on 2018-04-15 02:50

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_leave_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='jum_bg_color',
            field=models.CharField(default='#eeeeee', max_length=7, validators=[pages.models.layout_validation]),
        ),
        migrations.AddField(
            model_name='page',
            name='jum_text_color',
            field=models.CharField(default='#000000', max_length=7, validators=[pages.models.layout_validation]),
        ),
    ]
